### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by eonpatapon**
Basically, use of Album and Track instead of calling db methods directly.

As a bonus a context manager to beautifully get the sql cursor where needed :)

### CODE REVIEW

**Comment by gnumdk** [comment]
Another cool enhancement :)

**Comment by gnumdk** [comment]
And context manager is a cool thing to know !!

**Comment by gnumdk** [comment]
https://plus.google.com/u/0/104349425299854550670/posts/a7aeGUtefoe

**Comment by eonpatapon** [comment]
Hehe, thanks ;-)

**Pull request merged**
