### PR TITLE
Allow customisation of bindir and pythondir

### PR DESCRIPTION
**Pull request by Keepco**
This PR continues to further allow the customisation install dirs and tries to ( fully ) solve #1149 . Python.sysconfig_path strips the prefix, which isn't wanted if the python site directory doesn't reside within prefix/lib

### CODE REVIEW

**Comment by gnumdk** [comment]
Thanks ;)

**Comment by Keepco** [comment]
Yep, that's normal because python_prefix is a custom option and not built into meson

**Comment by gnumdk** [comment]
Patch reverted, was not working, please test before submitting pull request, I read the code but sometimes do not have time to test.

lollypop.in is not properly configured....

**Comment by Keepco** [comment]
Sorry, but I tested it on my system and it worked with both python prefix specified and without it. Guess I missed something, sorry

**Comment by gnumdk** [comment]
Ok, so it does not work on ArchLinux. Will give a look ASAP. But is an ArchLinux can give a look at this patch...

**Pull request merged**
