### PR TITLE
Add localization for Simplified Chinese

### PR DESCRIPTION
**Pull request by ksqsf**
This is an unfinished effort to address issue #1226 .

I introduced a `locale` package, submodule of which should export a function named `latinized_index`. It's later imported in 'utils'. This is how it works (zh_CN):
```
latinized_index('你好') # 'N', because the pronunciation is 'ni hao'
latinized_index('再见') # 'Z', because the pronunciation is 'zai jian'
latinized_index('1abc') # '#', because the first char is a digit
latinized_index('もも') # '…', because Japanese Hiragana is not recognizable in Chinese locale
latinized_index('Zoo') # 'Z', obviously
```

I changed one line (not in this pull request),
```
-        to_add = noaccents(c.upper())
+        to_add = latinized_index(noaccents(c.upper()))
```
and now the fast scroll looks good, except that '…' should be put after 'A'~'Z', and it doesn't work either.
fast scroll

The selection list is expected to work like this.
Android Contacts
(Photo taken from my Android phone)

To achieve this effect, I introduced 'categorize()' in utils.py:
```
categorize(['赵', 'Zoo', '马', 'Moo', '别', 'Boo', 'ももこ'])
# => {'…': ['ももこ'], 'B': ['Boo', '别'], 'M': ['Moo', '马'], 'Z': ['Zoo', '赵']}
```
Since the order of English and Chinese is not so important, here I simply use 'strxfrm' to sort strings in each group, which will put English before Chinese, but group '#' and group '…' should be put after 'A', ... 'Z'.

Last thing is to make selection works. I'm not familiar with GTK+. I guess we need a trasition from ListModel to TreeModel?

### CODE REVIEW

**Comment by gnumdk** [comment]
I guess you just need to edit fastscroll.py:
- Use your function in add_char()
- Update __check_value_to_mark() to use your function
- Update __on_button_press()

What could be cool is to check for language type and only import your code if needed.

**Comment by ksqsf** [comment]
Thanks for the helpful info! I'm busy these days, sorry for the late reply.

Clicking and showing the range now works, but still something to do: the list should be like: `Hoo, 胡 (hu), Moo, 木 (mu)`,  that is, names categoried according to its indices. Currently it looks like `Hoo, Moo, 胡, 木`.

Just to clarify, the only useful function I introduced is `latinized_index`, and whether to import it is decided by runtime locale as you can see in `locale/__init__.py`. If no locale is available, a fallback version which simply returns the first character is used. Hopefully that doesn't harm performance so much.

**Comment by gnumdk** [comment]
I do not understand what is doing this patch, can you post a screenshot (to see how it looks)?

**Comment by ksqsf** [comment]
ll
This is how it looks right now. 阿 (a) and 安 (an) should be under A. Clicking on 'A' takes me to artists whose names begin with A, leaving these artists unseen.

**Comment by gnumdk** [comment]
What is (a) and (an), chinese chars translation?

Sorting is done by python strcoll() function (localized.py) that should handle this.

**Comment by gnumdk** [comment]
@ksqsf No more time to work on this? I will be unable to finish this pull request as I don't really understand how it shoulds work ;)

**Comment by ksqsf** [comment]
@gnumdk I'm really sorry. I'm terribly busy this semester. I'll come back as soon as possible.

**Comment by gnumdk** [comment]
Don't be sorry, it's just because I'm sure this pull request is useful

**Comment by ksqsf** [comment]
I'll rework this PR within a few days.

**Pull request closed without merging**
