### PR TITLE
autotools to meson

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
This shouldn't be merged for few reasons:
- I don't understand why po/ & portal/ aren't on the same repo? Meson can't handle this, and it's needed in order to generate the desktop, appdata files
- I still didn't find out where the search-provider should be installed (will be fixed soon)

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
The build should work perfectly now with `meson >= 0.40.X`. 
It still requires the po files to generate the appdata & desktop files with the correct translations.  Either those should be moved to this repository or added as a git submodules.

**Comment by gnumdk** [comment]
It should be cool if you port lollypop-portal too ;)

For translations, I know about git submodules but did not take time to deal with it, can you do this from a pull request?

**Comment by bil-elmoussaoui** [comment]
So, do you want me to move the content of lollypop-portal to here? and move it to use meson too? or just use meson instead of autotools but on the other repository?

I will take care of that :+1:

**Comment by gnumdk** [comment]
No, lollypop portal needs to be a separate project. But just port it to use meson too :)

**Comment by gnumdk** [comment]
>The build should work perfectly now with meson >= 0.40.X

Does this means that I can't package anymore for old Fedora/OpenSUSE release?

**Comment by bil-elmoussaoui** [comment]
@gnumdk I don't use any of both distros. But as far as I know, meson is always updated as it doesn't depend on any other project (only Python). 
meson 0.41 is already on Fedora 24, 25, 26 :)
https://bodhi.fedoraproject.org/updates/?packages=meson

**Comment by bil-elmoussaoui** [comment]
@gnumdk Lollypop-portal was updated. We will need to add a meson.build to lollypop-po.
And should i port lollypop-help?

Can you please tell me the reason of splitting Lollypop files into different repositories?

**Comment by gnumdk** [comment]
No, just add them as sub git but I don't know how to do... The reason was to not have po changes in main repository.

**Comment by bil-elmoussaoui** [comment]
Alright :+1:  
Do i need to do that on a different  PR or on the same one?

**Comment by gnumdk** [comment]
Same one ;)

**Comment by gnumdk** [comment]
Take care of making lollypop-sp +x ;)

**Comment by bil-elmoussaoui** [comment]
Alright, i will fix that :) 
As you can see now in my fork https://github.com/bil-elmoussaoui/lollypop the help, po & portal are now submodules!

**Comment by gnumdk** [comment]
Thanks for your awesome work ;) You need to fix the branch conflict too since I just released 0.9.242.

**Comment by gnumdk** [comment]
Hmm, not portal, it needs to be outside of lollypop archive. Otherwise flatpak package will bundle the portal :)

**Comment by bil-elmoussaoui** [comment]
Makes sense

**Comment by bil-elmoussaoui** [comment]
The meson build system is now a little bit mature. I still need to update the lollypop-help repository in order to add a meson.build instead of a makefile. After that we can try building Lollypop using meson and see if we have any building issues

**Comment by gnumdk** [comment]
Keep the good work! Leaving autotools make my day ;)

**Comment by bil-elmoussaoui** [comment]
Can you take a look at the two PR on lollypop-po & lollypop-help? Once they're merged you can  try building lollypop by cloning my fork 
and running 

`meson builddir --prefix=/usr`
`sudo ninja -C builddir install`

**Comment by bil-elmoussaoui** [comment]
I've updated the README with the installation instructions & some small modifications! For Fedora & Debian installation instructions, appstream-glib-devel should be added but i don't have any idea about the package name :p

**Comment by gnumdk** [comment]
Meson encountered an error in file meson.build, line 7, column 7:
Assignment target must be an id.
gnome= = import('gnome')

**Comment by gnumdk** [comment]
After fixing this one:
Non-existent build file 'po/meson.build'

Shouldn't subrepo be downloaded automatically?

**Comment by gnumdk** [comment]
You should add this to the README.md:
$ git submodule init
$ git submodule update

**Comment by julianrichen** [comment]
You could avoid the `git submodule` commands if you make `po/` and `help/` into subprojects (since they kind of are).

Move `po/` and `help/` into `subproject/` directory, then update:

./meson.build
```meson
...
subproject ('po')
subproject ('help')
...
```

[po repo] ./meson.build
```meson
project ('lollypop-po', ...)

i18n = import ('i18n')

i18n.gettext (GETTEXT_PACKAGE, preset: 'glib')
```

[help repo] ./meson.build
```meson
project ('lollypop-help', ...)

gnome = import ('gnome')

gnome.yelp('meson',
  sources: [
    'C/index.page',
    'C/legal.xml'
  ],
  media: 'C/figures/lollypop-logo.png',
  symlink_media: false,
  languages: [
    'ca',
    'cs',
    'de',
    'es',
    'fi',
    'fr',
    'he',
    'it',
    'nl',
    'pl',
    'pt_BR',
    'ru',
    'sk',
    'sr',
    'uk',
    'sv'
  ],
)
```


Or make it a shell script with those `git submodule` commands using `run_command ()`. But I don't think that's the "Meson" way of doing it.

**Comment by bil-elmoussaoui** [comment]
Updated my PR & pushed new PR into lollypop-help & lollypop-po ! 
@julianrichen Thanks, i wasn't aware of subproject in meson :+1:

**Comment by gnumdk** [comment]
Meson encountered an error in file meson.build, line 28, column 0:
First statement must be a call to project

**Comment by bil-elmoussaoui** [comment]
Yeah because the two other PR are not merged yet. You can do that manually and try again :)

**Comment by gnumdk** [comment]
Merged but same error.

**Comment by bil-elmoussaoui** [comment]
`Submodule path 'po': checked out 'a631586428e6c944c13353b8212869b477bc32dc'`
It's still checking the old sha1 of an old commit.
 Or you can just `cd subprojects/po && git pull origin master` & the same thing for help subproject and everything should work as expected

**Comment by gnumdk** [comment]
$ ninja -C builddir install
ninja: Entering directory `builddir'
[3/4] Installing files.
Installing subdir /tmp/lollypop/data/icons/hicolor to /usr/local/share/icons/
Installing subdir /tmp/lollypop/lollypop to /usr/local/lib/python3.6/site-packages
Installing data/lollypop.gresource to /usr/local/share/lollypop/lollypop.gresource
Installing data/org.gnome.Lollypop.desktop to /usr/local/share/applications/org.gnome.Lollypop.desktop
Installing data/org.gnome.Lollypop.appdata.xml to /usr/local/share/appdata/org.gnome.Lollypop.appdata.xml
Installing /tmp/lollypop/data/org.gnome.Lollypop.gschema.xml to /usr/local/share/glib-2.0/schemas
Installing /tmp/lollypop/builddir/search-provider/lollypop-sp to /usr/local/bin
Installing /tmp/lollypop/builddir/search-provider/org.gnome.Lollypop.SearchProvider.service to /usr/local/share/dbus-1/services
Installing /tmp/lollypop/search-provider/lollypop-search-provider.ini to /usr/local/share/gnome-shell/search-providers
Installing /tmp/lollypop/builddir/lollypop to /usr/local/bin
Installing /tmp/lollypop/builddir/lollypop-cli to /usr/local/bin
Running custom install script '/usr/bin/python /usr/bin/meson --internal gettext install --subdir=subprojects/po --localedir=share/locale --pkgname=lollypop'
Installing /tmp/lollypop/builddir/subprojects/po/ca.gmo to /usr/local/share/locale/ca/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/da.gmo to /usr/local/share/locale/da/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/cs.gmo to /usr/local/share/locale/cs/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/de.gmo to /usr/local/share/locale/de/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/el.gmo to /usr/local/share/locale/el/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/en_IE.gmo to /usr/local/share/locale/en_IE/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/eo.gmo to /usr/local/share/locale/eo/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/es.gmo to /usr/local/share/locale/es/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/es_EC.gmo to /usr/local/share/locale/es_EC/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/fi.gmo to /usr/local/share/locale/fi/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/fr.gmo to /usr/local/share/locale/fr/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/ga.gmo to /usr/local/share/locale/ga/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/he.gmo to /usr/local/share/locale/he/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/hu.gmo to /usr/local/share/locale/hu/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/ka.gmo to /usr/local/share/locale/ka/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/id.gmo to /usr/local/share/locale/id/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/it.gmo to /usr/local/share/locale/it/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/lt.gmo to /usr/local/share/locale/lt/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/nl.gmo to /usr/local/share/locale/nl/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/pl.gmo to /usr/local/share/locale/pl/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/pt_PT.gmo to /usr/local/share/locale/pt_PT/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/pt_BR.gmo to /usr/local/share/locale/pt_BR/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/ro.gmo to /usr/local/share/locale/ro/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/ru.gmo to /usr/local/share/locale/ru/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/sk.gmo to /usr/local/share/locale/sk/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/sr.gmo to /usr/local/share/locale/sr/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/sr@latin.gmo to /usr/local/share/locale/sr@latin/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/sv.gmo to /usr/local/share/locale/sv/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/uk.gmo to /usr/local/share/locale/uk/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/tr.gmo to /usr/local/share/locale/tr/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/tr_TR.gmo to /usr/local/share/locale/tr_TR/LC_MESSAGES/lollypop.mo
Installing /tmp/lollypop/builddir/subprojects/po/zh_CN.gmo to /usr/local/share/locale/zh_CN/LC_MESSAGES/lollypop.mo
Running custom install script '/usr/bin/python /usr/bin/meson --internal yelphelper install --subdir=subprojects/help --id=meson --installdir=share/help --sources=C/index.page@@C/legal.xml --media=C/figures/lollypop-logo.png --langs=ca@@cs@@de@@es@@fi@@fr@@he@@it@@nl@@pl@@pt_BR@@ru@@sk@@sr@@uk@@sv'
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Error: cannot open XML file /tmp/lollypop/subprojects/help/C/C/index.page
Installing /tmp/lollypop/builddir/subprojects/help/ca/C/index.page to /usr/local/share/help/ca/meson/C/index.page
Traceback (most recent call last):
  File "/usr/bin/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 269, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 257, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/yelphelper.py", line 114, in run
    destdir, options.project_id, options.symlinks)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/yelphelper.py", line 69, in install_help
    shutil.copyfile(infile, outfile)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lollypop/builddir/subprojects/help/ca/C/index.page'
Failed to run install script '/usr/bin/python /usr/bin/meson --internal yelphelper install --subdir=subprojects/help --id=meson --installdir=share/help --sources=C/index.page@@C/legal.xml --media=C/figures/lollypop-logo.png --langs=ca@@cs@@de@@es@@fi@@fr@@he@@it@@nl@@pl@@pt_BR@@ru@@sk@@sr@@uk@@sv'
FAILED: install 
/usr/bin/python /usr/bin/meson --internal install /tmp/lollypop/builddir/meson-private/install.dat
ninja: build stopped: subcommand failed.

**Comment by bil-elmoussaoui** [comment]
Ops i forgot to change something on lollypop-help. 
Can you try changing the meson.build in lollypop-help to this ? 
```meson
project('lollypop-help')

if not meson.is_subproject()
    message('WARNING: This project is only intended to be used as a subproject!')
endif

gnome = import('gnome')

gnome.yelp('lollypop',
  sources: [
    'index.page',
    'legal.xml'
  ],
  media: 'figures/lollypop-logo.png',
  symlink_media: false,
  languages: [
    'ca',
    'cs',
    'de',
    'es',
    'fi',
    'fr',
    'he',
    'it',
    'nl',
    'pl',
    'pt_BR',
    'ru',
    'sk',
    'sr',
    'uk',
    'sv'
  ],
)
```
This should fix the issue. The build work correctly on my system

**Comment by gnumdk** [comment]
Yes, it works with this modification.

**Comment by bil-elmoussaoui** [comment]
@gnumdk I've created a PR for that :+1:

**Comment by gnumdk** [comment]
https://github.com/bil-elmoussaoui/lollypop/tree/master/subprojects

Look here, that's why subprojects are not updated, they are defining a commit!

**Comment by bil-elmoussaoui** [comment]
Now, with the PR merged into `lollypop-help` what's still needed to be done before this can be merged?

**Comment by gnumdk** [comment]
Fixing the subproject issue ;)

**Comment by gnumdk** [comment]
git submodule update --recursive --remote

**Comment by bil-elmoussaoui** [comment]
Submodules are now up to date & I've fixed the merge conflicts

**Comment by gnumdk** [comment]
lollypop-sp and it's dbus file are not installed by ninja. And you need to find a solution to make it +x

**Comment by bil-elmoussaoui** [comment]
`
Installing /home/bilal/lollypop/builddir/search-provider/lollypop-sp to /usr/bin
Installing /home/bilal/lollypop/builddir/search-provider/org.gnome.Lollypop.SearchProvider.service to /usr/share/dbus-1/services`
Is that the correct installation path ?

**Comment by gnumdk** [comment]
Yes

**Comment by gnumdk** [comment]
lollypop-sp needs to be in /usr/libexec, not in /usr/bin

**Comment by gnumdk** [comment]
Was wrong for dbus service file, it's installed.

**Comment by bil-elmoussaoui** [comment]
I've added a post install script which should
- Refresh icon cache
- Compile new schemas
- & make lollypop, lollypop-cli & lollypop-sp +x (executable)
I've also fixed the installation path for lollypop-sp

**Comment by gnumdk** [comment]
Perfect :)

**Comment by gnumdk** [comment]
AWESOME contribution ;)

**Comment by gnumdk** [comment]
The fun part will be next time I try to package Lollypop :-D

**Comment by bil-elmoussaoui** [comment]
If you've any issue just ping me here and I will try to help :+1: + the guys on #mesonbuild @freenode are awesome!

**Comment by gnumdk** [comment]
Should be easier to use, autotools was a pain :-(

**Comment by bil-elmoussaoui** [comment]
And MUCH more faster

**Comment by julianrichen** [comment]
@gnumdk For pacakging Meson just landed `meson dist` / `ninja dist` in 40.1 (or 41). Same as `make dist` in autotools.

**Comment by julianrichen** [comment]
Also congrats or porting to Meson. Meson is way better imo. Good job on the patch @bil-elmoussaoui.

**Comment by gnumdk** [comment]
@bil-elmoussaoui You have modified  shebang and this was not wanted. Using env is not wanted due to #1006

**Comment by bil-elmoussaoui** [comment]
Hmm, does the shebang has anything to do with the process name?

**Comment by gnumdk** [comment]
It seems... With env, you see the full python command.

**Comment by gnumdk** [comment]
PYTHON = join_paths(get_option('bindir'), 'python3')

I have added this for Eolie.... BTW, I'm far from having something working :-1:

**Comment by gnumdk** [comment]
msgfmt: cannot locate ITS rules for ../data/org.gnome.Eolie.appdata.xml.in
Warning: You are using 'ANSI_X3.4-1968' which is not a a Unicode-compatible locale.
You might see errors if you use UTF-8 strings as filenames, as strings, or as file contents.

**Comment by bil-elmoussaoui** [comment]
You can't assume that the binary of python 3 is called python3. As it's not the case on all distros out there

**Comment by gnumdk** [comment]
env python3 is doing the same.

**Comment by bil-elmoussaoui** [comment]
Nop with env, it will make sure the interpreter will use the first one defined in your $PATH

**Comment by gnumdk** [comment]
BTW it's not working as it is searching for /usr/local/bin/python3 :-1:

**Comment by gnumdk** [comment]
conf.set('PYTHON', python_bin.path())

\o/

**Comment by bil-elmoussaoui** [comment]
Perfect that you figured it out 👍

**Comment by gnumdk** [comment]
Yes, and Eolie now use Meson thanks to your work ;)

**Pull request merged**
