### PR TITLE
Prevent suspend while playing music

### PR DESCRIPTION
**Pull request by JasonLG1979**
Implements: https://github.com/gnumdk/lollypop/issues/1188

### CODE REVIEW

**Comment by enaut** [comment]
Works nicely! - tried the git build and everything worked as expected.

One thing though - my preference would be to only prevent suspend and not the screensaver. One could add a two options one for inhibit_idle and another for inhibit_suspend.

Or as I see it. As long as the screen is needed someone is close and interacting from time to time. As soon as no interaction is happening the chance for the screen to be needed is little - at least for me. So I'd say a sensible thing would be to leave the inhibit_idle out and just add an option for inhibit_suspend.

But anyhow much thanks for the fast response and work!

**Comment by JasonLG1979** [comment]
@enaut I've got a lot of stuff pending. Lots of bug fixes, some small, some major. This feature and a feature that allows the user to disable song change notifications. @gnumdk is going on vacation for a couple weeks if you want to do me a favor and give this branch a test.

https://github.com/JasonLG1979/lollypop/tree/mine

It's basically a combination of everything I'm working on.

**Comment by JasonLG1979** [comment]
> One thing though - my preference would be to only prevent suspend and not the screensaver. One could add a two options one for inhibit_idle and another for inhibit_suspend.

That would over complicate (code wise) an otherwise pretty simple feature IMHO. I don't know about that?

**Comment by enaut** [comment]
@JasonLG1979 I'll test your branch but only tomorrow or the day after tomorrow.

**Comment by enaut** [comment]
Just for you to note... I'm currently working on something to make the selection of what to inhibit more fine grained - will probably post something in three to five days. I'm completely new to Gtk development but with your patch I can find the relevant code parts easily. Also I noticed the fullscreen to inhibit too which I will try to include into the inhibitor file.

**Pull request closed without merging**
