### PR TITLE
Don't call Lp() over and over again

### PR DESCRIPTION
**Pull request by JasonLG1979**
app is already passed into the Mpris class might as well just use it as it's the same thing as Lp() (minus calling out to get app over and over again).

### CODE REVIEW

**Comment by gnumdk** [comment]
What is the issue with calling Gio.Application.get_default()?

Here, the issue is (for me): "WTF do I pass app to MPRIS?"

**Comment by JasonLG1979** [comment]
> What is the issue with calling Gio.Application.get_default()?

Nothing really. I doubt it adds really any overhead.

> Here, the issue is (for me): "WTF do I pass app to MPRIS?"

https://github.com/gnumdk/lollypop/blob/096ee13d08eb244a4c6904abfdf8cb43c809cd9a/lollypop/application.py#L177

**Comment by JasonLG1979** [comment]
The major benefit of PR is it makes the code more readable. self.__app is better than Lp() because what the hell is Lp()?

**Comment by JasonLG1979** [comment]
Even better would be ```self.__lollypop = app```

**Comment by bil-elmoussaoui** [comment]
@JasonLG1979 I think instead removing app from the argument sent to Server (MPRISServer here) is a better approach. Sadly python doesn't handle few things as in JS or Vala where you can just make the Main App class has a static property for its current instance and call it whenever you want. This will cause a loop issue in Python :p And @gnumdk avoids that by using Gio.application.get_default :+1:

**Comment by JasonLG1979** [comment]
> This will cause a loop issue in Python :p
There are no issues in passing app into mpris. In fact it's more "pythonic" then calling Lp() all the time IMHO.

**Comment by bil-elmoussaoui** [comment]
Yep, but in that case, you will have to pass app into a lot of other classes...Which isn't the best way to handle things. The best approach is to set some signals using GObject. The GObject classes aren't really pythonic anyway. You can't really create a 100% Pythonic Gtk Application using Python. Just from the first line on your first file, you will need to include Gtk or any other library, you will need to use `require_version('Gtk', '3.0')` before importing it which already don't follow PEP8... :/

**Comment by JasonLG1979** [comment]
> Yep, but in that case, you will have to pass app into a lot of other classes...Which isn't the best way to handle things. The best approach is to set some signals using GObject. The GObject classes aren't really pythonic anyway. You can't really create a 100% Pythonic Gtk Application using Python. Just from the first line on your first file, you will need to include Gtk or any other library, you will need to use require_version('Gtk', '3.0') before importing it which already don't follow PEP8... :/

True but it''s 6 of 1 thing 1/2 dozen another. Either you import LP in to every file as basically a constant or you pass app to the class. I much prefer passing it explicitly then having LP constants littered around. Plus there's readability which Lp fails at.

**Comment by gnumdk** [comment]
>there's readability which Lp fails at.

Not that hard to replace Lp() by APP or App or what else? :)

**Comment by JasonLG1979** [comment]
> Not that hard to replace Lp() by APP or App or what else? :)

No it's not. Feel free to disregard this PR if you like. To me it just made sense to use what was already passed into the class then importing some middle man fetcher.

**Comment by JasonLG1979** [comment]
I'll go ahead and close this as it seems to be a matter of philosophy and style and not objective "betterness".

**Comment by gnumdk** [comment]
The objective betterness should be to remove the app arg :)

**Comment by JasonLG1979** [comment]
> The objective betterness should be to remove the app arg :)

I guess as the owner of the repo that's ultimately up to you to decide. ;P

**Pull request closed without merging**
