### PR TITLE
Don't emit rate-changed signal until after it's been set in the db.

### PR DESCRIPTION
**Pull request by JasonLG1979**
Otherwise we get a stale rating in MPRIS. For example if the rating was 5 and we set it to 3 MPRIS would send back the old rating of 5 and not the new rating of 3. This fixes that by not emmiting the signal until after it's been set in the db.

### CODE REVIEW

**Comment by JasonLG1979** [comment]
For bonus points you could just send the rating and the Id in the signal so you could check the Id against the current song's Id to stop unnecessary metadata prop changed signals and avoid the round trip of calling back into the db. ATM you send a metadata prop changed signals every time any song is rated.

**Comment by JasonLG1979** [comment]
Done. Now we don't have to callback into the db for the new rating and we don't emit unneeded metadata prop change signals on rating changes.

**Comment by JasonLG1979** [comment]
Now ratings in MPRIS work as expected.

**Comment by gnumdk** [comment]
Thanks man ;)

**Comment by JasonLG1979** [comment]
No problem. I was wondering why do you call ```Lp()`` constantly when you from what I can tell just do ```self.__lollypop = Lp()``` at Class creation to grab the reference? Does the return value of ```Lp()``` ever change?

**Comment by gnumdk** [comment]
Lp() is just a shortcut to Gio.Application.get_default(). Do you really think calling this function everywhere is that expensive?

**Comment by JasonLG1979** [comment]
I doubt it, I wasn't sure what it was doing.

**Comment by JasonLG1979** [comment]
It just looked strange to me to be calling a function to grab something over and over again that didn't ever seem to change.

**Pull request merged**
