### PR TITLE
Simplify code with itertools and list comprehensions

### PR DESCRIPTION
**Pull request by eonpatapon**
Will add patches for other modules in this pull request later

### CODE REVIEW

**Comment by gnumdk** [comment]
Thanks ;)

**Comment by eonpatapon** [comment]
Have some problems with this patch. When choosing an album from the random list it just crash.

I'll try to find why.

**Comment by gnumdk** [comment]
Fixed ;)

**Comment by eonpatapon** [comment]
Good thanks ! :+1:

**Pull request merged**
