### PR TITLE
Add slovak translation

### PR DESCRIPTION
**Pull request by prescott66**
added slovak translation

### CODE REVIEW

**Comment by gnumdk** [comment]
Thanks for your pull request... Lollypop translators use https://www.transifex.com/
If you want, you can just join the project and request a new language...
Otherwise, i will just merge this pull request ;)

**Comment by prescott66** [comment]
I have translated it on transifex too.but long time was not merged...please merge it

**Comment by gnumdk** [comment]
Ah ok :) I merge translations before release so will happen soon,
Regards

**Comment by gnumdk** [comment]
Sorry, my fault in fact :-(

**Comment by prescott66** [comment]
ok. thanks :)

**Pull request closed without merging**
