### PR TITLE
Clean up a couple UI elements

### PR DESCRIPTION
**Pull request by JasonLG1979**
Fix a couple grammar mistakes and clean up the styling.

### CODE REVIEW

**Comment by enaut** [comment]
Everything works as far as I can test. So good work!
Stil in my opinion there could be some improvements made:

## ArtworkSearch.ui
Two issues in my opinion:
1. I wouldn't right align the custom search api link - the long space between the text and the link looks unexpected.
2. The Key field is too small for my api key and there seems to be enough space to make it bigger. (I have to scroll left and right as it is currently).

## SettingsDialog.ui
I don't know if people really understand what they have to do if they are not it-related. Maybe something along the lines of:

### Google API-Key
Google limits the amount of cover searches by default. To extend the limit you can create a custom API key with "Custom Search API" and "YouTube Data API" enabled here:  https://console.developers.google.com/apis

API key : [_______________]

**Comment by JasonLG1979** [comment]
I agree it's a little confusing. Just a tool tip and/or a link to "help" with a better explanation would be better than cluttering the settings window. I would guess that most users aren't going to go to the trouble of getting their own API key

**Comment by JasonLG1979** [comment]
The ability to enter the API key in the album art search popover also seems a bit redundant to me also.

**Comment by enaut** [comment]
Now that you mention it :) it really seems not the Gnome way to have more than one place to change a setting. So probably just remove the setting in the artwork dialog and add a larger text to the help file (especially since I created an api-key but I was rather lost on how to do it).

In the settings there could be just the API key Field with a link to the help file. That would probably make the whole thing more streamlined.

**Comment by d9h20f** [comment]
I think you have a point that most users won't create their own API key, so the option to enter a custom key should probably only be visible in dconf.

**Comment by JasonLG1979** [comment]
> I think you have a point that most users won't create their own API key, so the option to enter a custom key should probably only be visible in dconf.

I disagree. There still needs to be a way to enter it in the GUI otherwise it's not very discoverable.

**Comment by d9h20f** [comment]
You could say that about all of Lollypop's dconf-only options.

**Comment by JasonLG1979** [comment]
> You could say that about all of Lollypop's dconf-only options.

That's not really a good thing...

**Comment by JasonLG1979** [comment]
In my mind gserttings is for 2 things.

1. User options.
2. "Remembering" things like window position volume level and what not across sessions.

Any user option in gsettings should have a UI counter part.

**Pull request merged**
