### PR TITLE
Make desktop notifications at song changes optional

### PR DESCRIPTION
**Pull request by JasonLG1979**
Not everyone wants desktop notifications at song changes. This will make it a user option.

### CODE REVIEW

**Comment by gnumdk** [comment]
I'm ok with this pull request but:
- Please remove all settings code and keep this option hidden
- Please update string in gschema.xml as now disable-notifications only disable on song changed.

**Comment by JasonLG1979** [comment]
OK

**Comment by JasonLG1979** [comment]
The only other notification I've seen from Lollypop is the Google API nag. I really don't see the value in showing that <i>every time</i> the settings are shown?

**Comment by gnumdk** [comment]
Yes, you can remove it.

**Comment by gnumdk** [comment]
One more thing, please use pre-commit hooks available in Lollypop repository.

**Comment by JasonLG1979** [comment]
> One more thing, please use pre-commit hooks available in Lollypop repository

Not sure how to do that. Why not just integrate that into the repo at github?

**Comment by JasonLG1979** [comment]
But other than that done.

**Comment by JasonLG1979** [comment]
All notifications and song notifications are 2 different settings now. Ofc if you disable all notifications it will also disable song notifications.

**Comment by JasonLG1979** [comment]
The script is broken.

````
cd lollypop
cd hooks
./pre-commit.fedora
lollypop/*.py:1:1: E902 FileNotFoundError: [Errno 2] No such file or directory: 'lollypop/*.py'
```

I can just run the commands in the script though.

**Comment by JasonLG1979** [comment]
There done it passes all the hooks

**Comment by JasonLG1979** [comment]
> Yes, you can remove it.

What about the default "dummy API key" seems kinda confusing that the key is not actually used?

**Comment by JasonLG1979** [comment]
Found a couple more bugs trying to iron out this one.

1. Searching for album art with no API key was broken.
    the encoding was wrong and the attr field was wrong

2. Fixed and exception that prevents the user from resetting the songs db in the settings UI.

**Comment by enaut** [comment]
I tried to review as good as I understand it:
There is a working setting to disable song notifications
Tooltip is working too
The wording seems to be understandable and clear.

I think it is intended to not have any UI-Option for the "disable all notifications"

I did not test the youtube api key thing - I don't understand the changes made and don't know where youtube is used at all.

**Pull request merged**
