### PR TITLE
use ArgumentsParser instead of argv, clean the code a bit & add trans…

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
…lations support for help

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
It's seems that the code on lollypop-cli is outdated. 
`TypeError: add_album() missing 2 required positional arguments: 'rate' and 'remote'

**Comment by julianrichen** [comment]
Wouldn't using GTK's built in argument parser be better then bringing in another dependency?

Relevant functions:
* [add_main_option](https://lazka.github.io/pgi-docs/#Gio-2.0/classes/Application.html#Gio.Application.add_main_option)
* [add_main_option_entries](https://lazka.github.io/pgi-docs/#Gio-2.0/classes/Application.html#Gio.Application.add_main_option_entries)
* [handle_local_options (vfunc)](https://lazka.github.io/pgi-docs/#Gio-2.0/classes/Application.html#Gio.Application.do_handle_local_options)
* [do_command_line (vfunc)](https://lazka.github.io/pgi-docs/#Gio-2.0/classes/Application.html#Gio.Application.do_command_line)

I'm not 100% how it's done in Python as compared to C but pass the `Gio.ApplicationFlags.HANDLES_COMMAND_LINE` flag when you start the object. Then add an option in the `__init__`:

```python
self.add_main_option('example', ord('e'), GLib.OptionFlags.NONE, GLib.OptionArg.NONE, None)
```

and handle it in `do_command_line`:
```python
def do_command_line (self, command_line):
    options = command_line.get_options_dict ()

    if options.contains ('example'):
        # stuff for --example/-e flag

    self.do_activate ()

    return 0;
```

Pithos seems to have a good working example.

**Comment by bil-elmoussaoui** [comment]
I'm not bringing any new dependency, it's native Python package.

**Comment by gnumdk** [comment]
I also prefer to use the GTK way. As done in Lollypop.

**Comment by bil-elmoussaoui** [comment]
@gnumdk Alright, i will update my PR later

**Pull request closed without merging**
